name: tests macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        activate-environment: foo
    - name: conda
      run: |
          conda info
          conda list
    - name: Install dependencies
      run: |
        python --version
        conda clean -all
        conda clean --index-cache
        conda update conda
        conda install python=3.10.11
        conda install conda-forge::pygalmesh
        conda install -c conda-forge matplotlib numpy meshio scipy numba pycifrw dill xfab
        python -m pip install .
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=xfab
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
