name: tests macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        python --version
        sudo conda install python=3.10.11
        sudo conda install -c conda-forge matplotlib numpy meshio pygalmesh scipy numba pycifrw dill xfab
        python -m pip install .
    - name: Lint with flake8
      run: |
        sudo conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=xfab
    - name: Test with pytest
      run: |
        sudo conda install pytest
        pytest
